#pragma once
#ifndef __CAVALIA_DATABASE_PROFILERS_H__
#define __CAVALIA_DATABASE_PROFILERS_H__

#include "ExecutionProfiler.h"
#include "PhaseProfiler.h"
#include "CCExecutionTimeProfiler.h"
#include "CCExecutionCountProfiler.h"
#include "CCWaitTimeProfiler.h"
#include "CCAbortCountProfiler.h"
#include "CCAbortTimeProfiler.h"
#include "CCTsAllocTimeProfiler.h"
#include "CCMemAllocTimeProfiler.h"
#include "IndexTimeProfiler.h"
#include "CCWaitCountProfiler.h"

#if defined(MUTE)
#define INIT_PROFILERS ;

#define REPORT_PROFILERS ;

#else
#define INIT_PROFILERS\
	INIT_EXECUTION_PROFILER;\
	INIT_PHASE_PROFILER;\
	INIT_CC_EXECUTION_TIME_PROFILER;\
	INIT_CC_EXECUTION_COUNT_PROFILER;\
	INIT_CC_WAIT_TIME_PROFILER;\
	INIT_CC_WAIT_COUNT_PROFILER;\
	INIT_CC_ABORT_COUNT_PROFILER;\
	INIT_CC_ABORT_TIME_PROFILER;\
	INIT_CC_TS_ALLOC_TIME_PROFILER;\
	INIT_CC_MEM_ALLOC_TIME_PROFILER;\
	INIT_INDEX_TIME_PROFILER;

#define REPORT_PROFILERS\
	REPORT_EXECUTION_PROFILER;\
	REPORT_PHASE_PROFILER;\
	REPORT_CC_EXECUTION_TIME_PROFILER;\
	REPORT_CC_EXECUTION_COUNT_PROFILER;\
	REPORT_CC_WAIT_TIME_PROFILER;\
	REPORT_CC_WAIT_COUNT_PROFILER;\
	REPORT_CC_ABORT_COUNT_PROFILER;\
	REPORT_CC_ABORT_TIME_PROFILER;\
	REPORT_CC_TS_ALLOC_TIME_PROFILER;\
	REPORT_CC_MEM_ALLOC_TIME_PROFILER;\
	REPORT_INDEX_TIME_PROFILER;
#endif

#endif
